### ISSUE TITLE
Inventory Screen

### ISSUE THREAD

**Issue by cpluspluswiz** [Yixing-one/FarmConnect#12]
Users can access this screen from the farmer mode homepage.

Specifications:
1) Grid layout. (2 items per row)
2) Each item needs to have the following properties:
     - image of item
     - name of item
     - quantity (in pounds)
     - price per pound
 3) Search bar

Example?
<img width="480" alt="image" src="https://github.com/Yixing-one/FarmConnect/assets/49600019/9ebc37b6-c26c-4b65-aa65-61dd780ffc75">

link to material design: https://m2.material.io/components/cards#anatomy

**Comment by mr41haan29** [comment]
done.
