### ISSUE TITLE
Charity Mode (Farmers perspective And Charity Orgs perspective)

### ISSUE THREAD

**Issue by cpluspluswiz** [Yixing-one/FarmConnect#26]
Farmers Perspective:
- ability to make a post. In the create charity post screen, have the following:
   - choose items to add to the post and the quantity
when a post is made, deduct the quantity from the inventory db

Charity organizations perspective:
- fetch all the postings
- claim button or something that allows an org to "claim" a post

**Comment by mr41haan29** [comment]
done
