### ISSUE TITLE
Charity mode

### ISSUE THREAD

**Issue by cpluspluswiz** [Yixing-one/FarmConnect#8]
you can log into the charity mode as a farmer or charity organization:
Charity Org:
- orgs can make posts requesting fruits/vegetables and the quantity they need 
![image](https://github.com/Yixing-one/FarmConnect/assets/49600019/ac043a4f-91dd-454c-a30d-81cd75c4e279)
- can edit posts (add items, change the quantity)
![image](https://github.com/Yixing-one/FarmConnect/assets/49600019/37e8e5b6-de58-4531-9292-353ef5dc9c4b)
Farmer mode:
- make donations to posts made by charity organizations
![image](https://github.com/Yixing-one/FarmConnect/assets/49600019/2ea3fff1-04ea-4e4b-936e-cfea67351736)

**Comment by Yixing-one** [comment]
Done
